name: spectangle_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - scipy
  - astropy
  - h5py
  - pyyaml
  - matplotlib
  - tqdm
  - scikit-image
  - ipykernel
  - jupyterlab
  - black
  - ruff
  - pytest
  - pytest-cov
  - einops
  - pytorch::pytorch
  - pytorch::torchvision
  - pip:
      - synphot
      - dust_extinction
      - -e .         # install spectangle itself in editable mode (run from project root)